apiVersion: v2
appVersion: 2.12.1
dependencies:
- condition: openebs-ndm.enabled
  name: openebs-ndm
  repository: https://openebs.github.io/node-disk-manager
  version: 1.6.1
- condition: localpv-provisioner.enabled
  name: localpv-provisioner
  repository: https://openebs.github.io/dynamic-localpv-provisioner
  version: 2.12.1
- condition: cstor.enabled
  name: cstor
  repository: https://openebs.github.io/cstor-operators
  version: 2.12.1
- condition: jiva.enabled
  name: jiva
  repository: https://openebs.github.io/jiva-operator
  version: 2.12.2
- condition: zfs-localpv.enabled
  name: zfs-localpv
  repository: https://openebs.github.io/zfs-localpv
  version: 1.9.5
- condition: lvm-localpv.enabled
  name: lvm-localpv
  repository: https://openebs.github.io/lvm-localpv
  version: 0.8.2
- condition: nfs-provisioner.enabled
  name: nfs-provisioner
  repository: https://openebs.github.io/dynamic-nfs-provisioner
  version: 0.7.1
description: Containerized Storage for Containers
home: http://www.openebs.io/
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png
keywords:
- cloud-native-storage
- block-storage
- iSCSI
- storage
maintainers:
- email: kiran.mova@openebs.io
  name: kmova
- email: prateek.pandey@openebs.io
  name: prateekpandey14
name: openebs
sources:
- https://github.com/openebs/openebs
version: 2.12.7
