apiVersion: v2
appVersion: 5.4.17
description: A Helm chart to deploy Reflector
home: https://github.com/EmberStack/kubernetes-reflector
icon: https://raw.githubusercontent.com/EmberStack/CDN/master/Projects/ES.FX/es.fx.1.0.0.0.png
keywords:
- reflector
- controller
- copy
- secrets
- configmaps
- cert-manager
- certificates
maintainers:
- email: helm-charts@emberstack.com
  name: winromulus
name: reflector
sources:
- https://github.com/EmberStack/kubernetes-reflector
type: application
version: 5.4.17
