{{- if not .Values.loki.existingSecretForConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl .Values.loki.config . | nindent 4 }}
{{- end -}}
