{{- if .Values.rbac.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
rules:
  - apiGroups:      
      - policy
    resources:      
      - podsecuritypolicies
    verbs:          
      - use
    resourceNames:  
      - {{ include "loki.fullname" . }}
{{- end }}
