apiVersion: v2
appVersion: 0.5.0
description: CSI Driver for dynamic provisioning of LVM Persistent Local Volumes.
home: http://www.openebs.io/
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png
keywords:
- cloud-native-storage
- block-storage
- filesystem
- LVM
- Local Persistent Volumes
- storage
maintainers:
- email: prateek.pandey@mayadata.io
  name: prateekpandey14
- email: pawan@mayadata.io
  name: pawanpraka1
name: lvm-localpv
sources:
- https://github.com/openebs/lvm-localpv
version: 0.5.0
