annotations:
  artifacthub.io/changes: |
    - "[Changed]: Use helm-docs to generate README.md"
apiVersion: v2
appVersion: v1.1.1
description: A Helm chart for ArgoCD notifications, an add-on to ArgoCD.
home: https://github.com/argoproj/argo-helm
icon: https://argocd-notifications.readthedocs.io/en/stable/assets/logo.png
keywords:
- argoproj
- argocd
- argocd-notifications
maintainers:
- name: alexmt
- name: andyfeller
name: argocd-notifications
type: application
version: 1.5.2
