annotations:
  artifacthub.io/changes: |
    - "[Added]: Support annotations on secret objects"
apiVersion: v2
appVersion: 1.1.1
description: A Helm chart for ArgoCD notifications, an add-on to ArgoCD.
home: https://github.com/argoproj/argo-helm
icon: https://argocd-notifications.readthedocs.io/en/stable/assets/logo.png
keywords:
- argoproj
- argocd
- argocd-notifications
maintainers:
- name: alexmt
- name: andyfeller
name: argocd-notifications
type: application
version: 1.5.1
