apiVersion: v2
appVersion: v0.1.0
description: A Helm chart for installing ArgoCD ApplicationSet
home: https://github.com/argoproj/argo-helm
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
keywords:
- argoproj
- appset
- gitops
maintainers:
- name: maruina
name: argocd-applicationset
type: application
version: 0.1.6
