annotations:
  artifacthub.io/changes: |
    - Add custom annotations to ScaledObject
    - Adding quotes in the serviceAccount name in Helm values
    - Remove ClusterRole when scope option is enabled
    - Update kube-webhook-certgen image to v1.5.1
apiVersion: v2
appVersion: 0.43.0
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer
home: https://github.com/kubernetes/ingress-nginx
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
- ingress
- nginx
kubeVersion: '>=1.16.0-0'
maintainers:
- name: ChiefAlexander
name: ingress-nginx
sources:
- https://github.com/kubernetes/ingress-nginx
type: application
version: 3.21.0
