apiVersion: v2
appVersion: v2.12.5
dependencies:
- condition: minio.install
  name: minio
  repository: https://helm.min.io/
  version: 8.0.9
description: A Helm chart for Argo Workflows
home: https://github.com/argoproj/argo-helm
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
maintainers:
- name: alexec
- name: alexmt
- name: jessesuen
- name: benjaminws
name: argo
version: 0.16.2
