apiVersion: v1
kind: Secret
metadata:
  name: "bootstrap-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "bootstrap-secret" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- if $existingSecret.data.bootstrapPassword }}
  bootstrapPassword: {{ $existingSecret.data.bootstrapPassword }}
    {{- else }}
  bootstrapPassword: {{ .Values.bootstrapPassword | default "" | b64enc | quote }}
    {{- end }}
  {{- else }}
  bootstrapPassword: {{ .Values.bootstrapPassword | default "" | b64enc | quote }}
  {{- end }}
