annotations:
  artifacthub.io/changes: |
    - "[Added]: Add support for Google ManagedCertificate on GKE
    - "[Added]: Add support for Google FrontendConfig on GKE
apiVersion: v2
appVersion: v2.2.2
dependencies:
- condition: redis-ha.enabled
  name: redis-ha
  repository: https://dandydeveloper.github.io/charts/
  version: 4.12.17
description: A Helm chart for ArgoCD, a declarative, GitOps continuous delivery tool
  for Kubernetes.
home: https://github.com/argoproj/argo-helm
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
keywords:
- argoproj
- argocd
- gitops
maintainers:
- name: alexec
- name: alexmt
- name: jessesuen
- name: seanson
name: argo-cd
version: 3.30.0
